version: '3'

services:
  find-club:
    image: go:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./log:/app/log
      - ./src:/app/src
    ports:
      - "3302:8080"
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_PATH_PREFIX=/app/src/config/
      - ENV=dev
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io


    container_name: find-club
    command: bash -c "cd /app/src && go run main.go"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.3
    container_name: find-club-mongo
    ports:
      - '3303:27017'
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=findclub

